### ISSUE TITLE
Frija_v2.0.22044.1

### ISSUE THREAD

**Issue by morethanhater** [SlackingVeteran/frija-dev#6]
It won't boot.
I did restart PC, and yet no luck.

![image](https://user-images.githubusercontent.com/36857282/183055307-b6ada1e2-38b8-42fb-ade9-7374212104c8.png)

![image](https://user-images.githubusercontent.com/36857282/183055131-6497641a-d8d9-4efa-80cd-9d201478d8a3.png)

**Comment by Usamakhursheed** [comment]
Use WIndowsDesktop-Runtime x86

**Comment by Usamakhursheed** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.28-windows-x86-installer

**Comment by morethanhater** [comment]
> https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.28-windows-x86-installer

Will try and give feedback

**Comment by morethanhater** [comment]
> Use WIndowsDesktop-Runtime x86

as you can see at screenshot which i did provide at first post - it's already installed.
your solution is good but kinda worthless in spite of this issue.
thanks for suggestion.

**Comment by MASTERdjango** [comment]
hello dude... here the one that will make it work....
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.10-windows-x86-installer

**Comment by byyxx128** [comment]
## You got the wrong runtime.
As Frija is a desktop program, you need the **.NET Desktop Runtime** rather than ~~**.NET Runtime**~~ as well.
![image](https://user-images.githubusercontent.com/20079289/191395823-4bfb74f3-f1a8-477a-b6c0-2af5f4aae348.png)
![image](https://user-images.githubusercontent.com/20079289/191395890-ef09f44d-b8fc-49ca-b62e-ab66a6407546.png)
### As the solution, you need to do the following steps.
1. Uninstall all your existing .NET Core runtime. A reboot is recommended.
2. Download and install the latest .NET Core 3.1 Desktop Runtime.
If you download from the official website manually, make sure you download the **.NET Desktop Runtime** rather than ~~**.NET Runtime**~~.
https://dotnet.microsoft.com/download/dotnet/3.1
![image](https://user-images.githubusercontent.com/20079289/191396489-9680765c-1941-4cf6-a452-e73f2a2eba23.png)
https://dotnet.microsoft.com/download/dotnet/3.1/runtime
![image](https://user-images.githubusercontent.com/20079289/191397713-b3c4ebd3-f8e3-4400-8df5-bdff3905364e.png)
3. Check if you have the right .NET Core Desktop Runtime.
![image](https://user-images.githubusercontent.com/20079289/191395890-ef09f44d-b8fc-49ca-b62e-ab66a6407546.png)
4. You should be able to execute Frija now.

**Comment by StevePritchard** [comment]
Even if you can get Frija running it seems unable to connect to the FUS server.  Is it working for you guys?

**Comment by Ushie** [comment]
> Even if you can get Frija running it seems unable to connect to the FUS server. Is it working for you guys?

Frija 2.x can't connect to the DB atm and SlackingVeteran is busy, however Frija 1.4. x is functional

**Comment by byyxx128** [comment]
The version [v2.0.22044.1](https://github.com/SlackingVeteran/frija-dev/releases/tag/v2.0.22044.1) did work before, but it's not working now. I got the error `Could not connect to FUS server for nonce`.

I guess I know the reasion. Your guys can try [v2.0.21355.3](https://github.com/SlackingVeteran/frija-dev/releases/tag/v2.0.21355.3). It works fine for me.
* If it tells you a new update is available, close it and start again, then you should be able to use it directly.

If v2.0.21355.3 works for you as well, I will new issue to mension the author/developer.

**Comment by byyxx128** [comment]
The version [v2.0.22044.1](https://github.com/SlackingVeteran/frija-dev/releases/tag/v2.0.22044.1) did work before, but it's not working now. I got the error `Could not connect to FUS server for nonce`.

I guess I know the reason. Your guys can try [v2.0.21355.3](https://github.com/SlackingVeteran/frija-dev/releases/tag/v2.0.21355.3). It works fine for me.
* If it tells you a new update is available, close it and start again, then you should be able to use it directly.

If v2.0.21355.3 works for you as well, I will new issue to mension the author/developer.

**Comment by SlackingVeteran** [comment]
User had wrong .net runtime. Link to install correct one is provided in Readme file
